### ISSUE TITLE
Hyprscrolling fails to build

### ISSUE THREAD

**Issue by AshPie3** [hyprwm/hyprland-plugins#637]
Using `hyprland 0.54.3` when trying to install hyprland plugins two plugins fail to build hyprscrolling and hyprbars. 

When using verbose output of hyprscrolling build the error shows:
```
Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/<user> && PKG_CONFIG_PATH="/var/cache/hyprpm/<user>/headersRoot/share/pkgconfig:$PKG_CONFIG_PATH" make -C hyprscrolling all
make: Entering directory '/run/user/1000/hyprpm/<user>/hyprscrolling'
g++ -O2 -shared -fPIC -std=c++2b  --no-gnu-unique main.cpp Scrolling.cpp -o hyprscrolling.so `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon`
In file included from main.cpp:20:
Scrolling.hpp:4:10: fatal error: hyprland/src/layout/IHyprLayout.hpp: No such file or directory
    4 | #include <hyprland/src/layout/IHyprLayout.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from Scrolling.cpp:1:
Scrolling.hpp:4:10: fatal error: hyprland/src/layout/IHyprLayout.hpp: No such file or directory
    4 | #include <hyprland/src/layout/IHyprLayout.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:12: all] Error 1
make: Leaving directory '/run/user/1000/hyprpm/<user>/hyprscrolling'


✖ Plugin hyprscrolling failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.
```

I tried using older releases of the plugins but it didn't help.
Do I need to switch to hyprland-git?

**Comment by fufexan** [comment]
Plugins haven't been updated to work with versions newer than 0.53.

Hyprland is in the middle of some rewrites, so plugins will have to wait until that's done.

**Comment by fufexan** [comment]
Also you don't need the hyprscrolling plugin anymore, as it's been integrated as a core layout in Hyprland.

**Comment by vaxerski** [comment]
yes hyprscrolling is deprecated
